/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WeirdoContract } from "./WeirdoContract";

export { WeirdoContract__factory } from "./factories/WeirdoContract__factory";
